Setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasks.urls')),
    path('',include('usuarios.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  

apps/usuarios/urls.py
from django.urls import path
from usuarios.views import *


urlpatterns = [
    path("perfil/<str:amigo_id>", perfil, name='perfil'),
    path('remover/<int:amigo_id>',removerAmigo ,name="removerAmigo"),
    path('adiconar/<int:amigo_id>', adicionarAmigo ,name="adicionarAmigo"),
    path("login", login, name='login'),
    path("cadastrar-se", cadastro, name='cadastro'),
    path("cadastro/perfil", userProfile, name='userProfile'),
    path("logout", logout, name='logout'),
    path('usuarios', buscaUsuarios, name='usuario'),
]    

apps/usuarios/models.py
from django.contrib.auth.models import User
from django.db import models
import os


upload_to = 'avatar'

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100, default='')
    sobrenome = models.CharField(max_length=100, default='')
    empresa = models.CharField(max_length=100, default='')
    avatar = models.FileField(upload_to=upload_to, default='', blank=True)
    

    def __str__(self):
        return self.user.username
    
STATUS_CHOICES = (
    ('enviado','Enviado'),
    ('aceito','Aceito'),
    ('recusado','Recusado')
)

class Relationship(models.Model):
    sender = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateField(auto_now=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self): 
        return f'{self.sender}-{self.receiver}-{self.status}'
    

    

apps/usuarios/forms.py
from django import forms
from usuarios.models import *

class LoginForms(forms.Form):
    nome_login = forms.CharField(
        label="Login",
        required= True,
        max_length= 100,
        widget= forms.TextInput(
            attrs={
                "placeholder":'Usuario:'
            }
        )
    )
    senha = forms.CharField(
        label='Senha',
        required=True,
        max_length=30,
        widget= forms.PasswordInput(
            attrs={
                "placeholder":'Senha:'
            }
        )
    )

class CadastroForms(forms.Form):
    nome_cadastro=forms.CharField(
        label='Login', 
        required=True, 
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'input-login',
                'placeholder': 'Usuário',
            }
        )
    )
    email=forms.EmailField(
        label='Email',
        required=True,
        max_length=100,
        widget=forms.EmailInput(
            attrs={
                'class': 'input-login',
                'placeholder': 'Email',
            }
        )
    )
    senha_1=forms.CharField(
        label='Senha', 
        required=True, 
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'class': 'input-login',
                'placeholder': 'Senha',
            }
        ),
    )
    senha_2=forms.CharField(
        label='Senha2', 
        required=True, 
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'class': 'input-login',
                'placeholder': 'Senha novamente',
            }
        ),
    )
   
    def clean_nome_cadastro(self):
        nome = self.cleaned_data.get('nome_cadastro')

        if nome:
            nome = nome.strip()
            if ' ' in nome:
                raise forms.ValidationError('Espaços não são permitidos nesse campo')
            else:
                return nome

    def clean_senha_2(self):
        senha_1 = self.cleaned_data.get('senha_1')
        senha_2 = self.cleaned_data.get('senha_2')

        if senha_1 and senha_2:
            if senha_1 != senha_2:
                raise forms.ValidationError('Senhas não são iguais')
            else:
                return senha_2
            




from django import forms
from .models import UserProfile

class UserProfileForms(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['nome', 'sobrenome', 'empresa', 'avatar']
        widgets = {
            'nome': forms.TextInput(attrs={
                'class': 'input-login',
                'placeholder': 'Nome',
            }),
            'sobrenome': forms.TextInput(attrs={
                'class': 'input-login',
                'placeholder': 'Sobrenome',
            }),
            'empresa': forms.TextInput(attrs={
                'class': 'input-login',
                'placeholder': 'Empresa',
            }),
            'avatar': forms.FileInput(attrs={
                'class': 'input-login',  # Ajuste as classes conforme necessário
            }),
        }

apps/usuarios/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.contrib.auth.models import User
from django.contrib import auth
from .models import UserProfile, Relationship
from tasks.models import RelationshipEquipe
from django.contrib.auth.decorators import login_required
from tasks.models import Projeto, RelationshipTarefa
from usuarios.forms import LoginForms, CadastroForms, UserProfileForms
from django.contrib import messages


def login(request):
    if request.user.is_authenticated:
        return redirect('home')
    form = LoginForms()
    if request.method == 'POST':
        form = LoginForms(request.POST)
        try:
            if form.is_valid():
                nome = form['nome_login'].value()
                senha = form['senha'].value()
            usuario = auth.authenticate(
                request,
                username=nome,
                password=senha
            )
        except:
            return redirect('login')
        if usuario is not None:
            auth.login(request, usuario)
            return redirect('home')
        else:
            messages.error(request,"Falha ao Logar!")
            return redirect('login')
    return render(request, 'usuarios/login.html', {'form': form})


def cadastro(request):
    if request.user.is_authenticated:
        return redirect('home')
    form = CadastroForms()
    if request.method == 'POST':
        form = CadastroForms(request.POST)
        if form['senha_1'].value() != form['senha_2'].value():
            messages.error(request,'As Senhas deve ser igual!')
            return redirect('cadastro')
        login = form['nome_cadastro'].value()
        email = form['email'].value()
        senha = form['senha_2'].value()

        if User.objects.filter(username=login).exists(): 
            messages.error(request,'Usuario já Existe')
            return redirect('cadastro')

        usuario = User.objects.create_user(
            username=login,
            email=email,
            password=senha,
        )    

        logar = auth.authenticate(
            request,
            username=login,
            password=senha
        )
        auth.login(request, logar)
        messages.success(request,"Cadastro feito com Sucesso")
        return redirect('userProfile')
    return render(request, 'usuarios/cadastro.html', {'form': form})


def userProfile(request):
    if not request.user.is_authenticated:
        return redirect('login')
    user_profile = request.user.userprofile
    form = UserProfileForms()
    if request.method == 'POST':
        form = UserProfileForms(request.POST, request.FILES, instance=user_profile)
        login = form['nome'].value()
        sobrenome = form['sobrenome'].value()
        empresa = form['empresa'].value()
        avatar = form['avatar'].value        
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            print("Erros de validação:", form.errors)
    else:
        form = UserProfileForms(instance=user_profile)
    return render(request, 'usuarios/userProfile.html', {'form': form})


def logout(request):
    auth.logout(request)
    return redirect('login')

@login_required(login_url='login')
def perfil(request, amigo_id=None):
    '''Pagina de Perfil do Usuario mostrando Amigos, Projetos e Tarefas'''
    user_profile = request.user.userprofile
    notificacaoEquipe = RelationshipEquipe.objects.filter(convidado=user_profile,status='enviado')
    notificacaoAmigo = Relationship.objects.filter(receiver=user_profile, status='enviado')
    notificacao = len(notificacaoEquipe) + len(notificacaoAmigo)
    usuario = UserProfile.objects.get(user=amigo_id)
    amigos = Relationship.objects.filter(sender=usuario, status='aceito')
    tarefas = RelationshipTarefa.objects.filter(usuario=usuario)
    todosProjetos = Projeto.objects.filter(equipe__usuario=usuario)
    relacionamentos = Relationship.objects.filter(sender=user_profile) 
    frindes = []
    for relacionado in relacionamentos:
        frindes.append(relacionado.receiver)
    if usuario == user_profile:
        situacao = ''
    elif usuario in frindes:
        situacao = Relationship.objects.get(sender=user_profile, receiver=usuario)
    else:
        situacao = "nenhum"

    if amigos.count == 0:
        amigos = 'Sem amigos'
    return render(request,'usuarios/perfil.html', {'projetos':todosProjetos,'usuario':usuario, 'amigos':amigos, 'notificacao':notificacao, 'tarefas':tarefas, "situacao":situacao})


@login_required(login_url='login')
def removerAmigo(request, amigo_id):
    user_profile = request.user.userprofile
    amigo = get_object_or_404(UserProfile, id=amigo_id)
    Relationship.objects.filter(sender=user_profile, receiver=amigo).delete()
    Relationship.objects.filter(receiver=user_profile, sender=amigo).delete()
    current_url = request.META.get('HTTP_REFERER', '/')
    return redirect(current_url)

def adicionarAmigo(request, amigo_id):
    user_profile = request.user.userprofile
    amigo = get_object_or_404(UserProfile, id=amigo_id)
    current_url = request.META.get('HTTP_REFERER', '/')
    if  Relationship.objects.filter(sender=user_profile, receiver=amigo, status='enviado').exists() or Relationship.objects.filter(sender=amigo, receiver=user_profile, status='enviado').exists():
        return redirect(current_url)
    else:
        Relationship.objects.create(sender=user_profile, receiver=amigo, status='enviado')
        return redirect(current_url)



@login_required(login_url='login')
def buscaUsuarios(request):
    user_profile = request.user.userprofile
    notificacaoEquipe = RelationshipEquipe.objects.filter(convidado=user_profile,status='enviado')
    notificacaoAmigo = Relationship.objects.filter(receiver=user_profile, status='enviado')
    notificacao = len(notificacaoEquipe) + len(notificacaoAmigo)
    todosProjetos = Projeto.objects.filter(equipe__usuario=user_profile)
    if "usuario" in request.GET:
        nome = request.GET['usuario']
        nome = nome.capitalize()
        usuarios = UserProfile.objects.filter(nome__icontains=nome)
        amigos = Relationship.objects.filter(sender=user_profile ,receiver__nome__icontains=nome)
        listaEnviado = []
        listaAmigo = []
        listaUsuario = []
        for amigo in amigos:
            if amigo.receiver != user_profile:
                if amigo.status == "aceito":
                    listaAmigo.append(amigo.receiver)
                else:
                    listaEnviado.append(amigo.receiver)
        for usuario in usuarios:
            if not usuario in listaAmigo and usuario != user_profile and not usuario in listaEnviado:
                listaUsuario.append(usuario)
    return render(request,'usuarios/buscaAmigos.html', {'projetos':todosProjetos, 'usuarios':listaUsuario, 'amigos':listaAmigo , 'notificacao':notificacao})

templates/usuarios/buscaAmigos.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <section id='notificacoes'>
        <div class="notificacoes">
            <h2> Usuários </h2>
            {% if usuarios.count == 0 %}
                <h3>Nenhuma Perfil Encontrado</h3>
            {% else %}
            {% for amigo in amigos %}
                <div class='notificacao'>

                    <div class='icone-notificacao'>
                        {% if not  amigo.avatar %}
                            <img src="{% static 'media/icones/do-utilizador (2).png' %}" alt="">
                        {% else %}  
                            <img src="{{ amigo.avatar.url }}"alt="foto">
                        {% endif %}
                    </div>
                    <div class='notificacao-dados'>
                        <a href="{% url "perfil" amigo.user.id %}">
                            <p><strong>{{amigo.nome}} {{amigo.sobrenome}}</strong></p>
                            <p>{{amigo.empresa}}</p>
                        </a>
                    </div>
                    <div class='notificacao-opcoes'>
                        <a href="{% url "removerAmigo" amigo.id %}"><div class='notificacao-opcao aceitar'><img src="{% static 'media/icones/rejeitar.png'%}" alt=""></div></a>
                    </div>
                    
                </div>
            
            {% endfor %}
            {% for usuario in usuarios %}
                <div class='notificacao'>
                    <div class='icone-notificacao'>
                        {% if not usuario.avatar %}
                            <img src="{% static 'media/icones/do-utilizador (2).png' %}" alt="">
                        {% else %} 
                            <img src="{{ usuario.avatar.url }}"alt="foto">
                        {% endif %}
                    </div>
                    <div class='notificacao-dados'>
                        <a href="{% url "perfil" usuario.user.id %}">
                            <p><strong>{{usuario.nome}} {{usuario.sobrenome}}</strong></p>
                            <p>{{usuario.empresa}}</p>
                        </a>
                    </div>
                    <div class='notificacao-opcoes'>
                        <a href="{% url "adicionarAmigo" usuario.id %}"><div class='notificacao-opcao aceitar'><img src="{% static 'media/icones/enviar.png'%}" alt=""></div></a>
                    </div>
                </div>
            
            {% endfor %}
            {% endif %}
        </div>
    </section>
{% endblock %}

templates/usuarios/cadastro.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<section id='login'>
    {% for message in messages %}
        <div class='{{message.tags}}'> 
            <p> <strong>{{ message }}</strong></p> 
        </div>
    {% endfor %}
    <div id="header-login">
        <a  id='icone-cadastro' href="{% url 'login' %}"><div > <strong>Login</strong> </div></a>
        <div id='icone-login'> <p><strong>Cadastrar-se</strong></p> </div>
    </div>
    <form id='formulario-login' action="{% url 'cadastro'  %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        
        <div>
            {% for field in form.visible_fields %}
            <div class='label-login'>
                <label for="{{orm.id_for_label}}">  
                    {% if field.label == "Login" %}
                        <img src="{% static 'media/icones/do-utilizador (2).png'%}" alt="">
                    {% elif field.label == "Email" %}
                        <img src="{% static 'media/icones/o-email.png'%}" alt="">
                    
                    {% elif field.label == "Senha" %}
                        <img src="{% static 'media/icones/cadeado.png'%}" alt="">
                    {% elif field.label == "Senha2" %}
                        <img src="{% static 'media/icones/cadeado.png'%}" alt="">
                    {% endif %}
                </label>
                    {{field}}
    
                </div>
            {% endfor %}
        </div>

        <button id='botao-cadastro' type='submit'> <h2><strong>Cadastrar-se</strong></h2></button>    
    </form>
   
</section>
{% endblock %}

templates/usuarios/editar-perfil.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

{% endblock %}

templates/usuarios/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section id='login'>
    {% for message in messages %}
        <div class='{{message.tags}}'> 
            <p><strong> {{ message }}</strong></p> 
        </div>
    {% endfor %}
    <div id="header-login">
        <div id='icone-login'> <p><strong>Login</strong></p> </div>

        <a id='icone-cadastro' href="{% url 'cadastro' %}"><div> <p ><strong>Cadastrar-se</strong></p></div>  </a>
    </div>
    <form id='formulario-login'action="{% url 'login'  %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        
        <div>
            {% for field in form.visible_fields %}
            <div class='label-login'>
                <label for="{{orm.id_for_label}}">  
                    {% if field.label == "Login" %}
                        <img src="{% static 'media/icones/do-utilizador (2).png'%}" alt="">
                    {% elif field.label == "Senha" %}
                        <img src="{% static 'media/icones/cadeado.png'%}" alt="">
                    {% endif %}
                </label>
                {% if field.label == "Login" %}
                    <input class="input-login" type="text" name="nome_login" placeholder="Usuário" maxlength="100" required="" id="id_nome_login">
                
                {% elif field.label == "Senha" %}
                    <input class="input-login" type="password" name="senha" placeholder="Senha" maxlength="30" required="" id="id_senha">
                {% endif %}
            </div>
            {% endfor %}
        </div>
        <button id='botao-login' type='submit'> <h2><strong>Entrar</strong></h2></button>    
    </form>

</section>
{% endblock %}

templates/usuarios/notificacao.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <section id='notificacoes'>
        <div class="notificacoes">
            <h2> Notificações </h2>
            {% if notificacaoAmigo.count == 0 %}
                <h3>Nenhuma Solicitação de Amizade</h3>
            {% else %}
                <p>Solicitação de Amizade ({{notificacaoAmigo.count}})</p>
            {% endif %}
            {% for notificacao in notificacaoAmigo   %}
                <div class='notificacao'>
                    <div class='icone-notificacao'>
                        {% if not notificacao.sender.avatar %}
                        
                            <img src="{% static 'media/icones/do-utilizador (2).png' %}" alt="">
                        {% else %}
                            <img src="{{ notificacao.sender.avatar.url }}"alt="foto">
                        {% endif %}
                    </div>
                    <div class='notificacao-dados'>
                        <a href="{% url "perfil" notificacao.sender.user.id %}">
                            <p><strong>{{notificacao.sender.nome}}</strong></p>
                            <p>{{notificacao.sender.empresa}}</p>
                            
                        </a>
                    </div>
                    <div class='notificacao-opcoes'>
                        <a href="{% url 'atualizar_status' 'relationship' notificacao.id 'recusado' %}"><div class='notificacao-opcao recusar'><img src="{% static 'media/icones/rejeitar.png'%}" alt=""></div></a>
                        <a href="{% url 'atualizar_status' 'relationship' notificacao.id 'aceito' %}"><div class='notificacao-opcao aceitar'><img src="{% static 'media/icones/aceitar.png'%}" alt=""></div></a>
                    </div>
                </div>
            {% endfor %}
            {% if notificacaoEquipe.count == 0 %}
                <h3>Nenhuma Solicitação de Equipe</h3>
            {% else %}
                <p>Solicitação de Equipe ({{notificacaoEquipe.count}}) </p>
            {% endif %}
            {% for notificacao in notificacaoEquipe %}
                <div class='notificacao'>
                    <div class='notificacao-projeto' id="tipo" style="background-color: {{ notificacao.projeto.cor }}; box-shadow: 0px 0px 6px {{ notificacao.projeto.cor }};">
                        <p><strong>{{ notificacao.projeto.titulo|slice:":2" }}</strong></p>
                    </div>
                    <div class='notificacao-dados'>
                        <p><strong>{{ notificacao.projeto.titulo }}</strong></p>
                    </div>
                    <div class='notificacao-opcoes'>
                        <a href="{% url 'atualizar_status' 'relationship_equipe' notificacao.id 'recusado' %}"><div class='notificacao-opcao recusar'><img src="{% static 'media/icones/rejeitar.png'%}" alt=""></div></a>
                        <a href="{% url 'atualizar_status' 'relationship_equipe' notificacao.id 'aceito' %}"><div class='notificacao-opcao aceitar'><img src="{% static 'media/icones/aceitar.png'%}" alt=""></div></a>
                     </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/usuarios/perfil.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section id='perfil'>
    <div id='perfil-tela'>
        <div id='perfil-tela-dividida'>
    
            
            <div id='header-perfil'>
                <div id="icone-perfil">
                {% if not usuario.avatar %}
                    <img src="{% static 'media/icones/do-utilizador (2).png' %}" alt="">
                {% else %}
                    <img src="{{ usuario.avatar.url }}" alt="foto">
                {% endif %}
                </div>
                <div id='pessoal-perfil'>
                    <h4> <strong>{{ usuario.nome }} {{usuario.sobrenome}}</strong></h4>
                    <p> {{ usuario.empresa }}</p>
                </div>
            </div>  
            
            {% if usuario.user.id == user.id %}
            <div id='info-perfil'>
                <a href="{% url 'userProfile'  %}"><div id='editar-perfil'> <p><strong>Editar Perfil</strong></p> </div></a>
            </div>
            {% else %}
           
                {% if situacao.status == "enviado" %}
                <div id='info-perfil'>
                    <a href=""><div id='editar-perfil'> <p><strong>Enviado</strong></p> </div></a>
                </div>
                {% elif situacao.status == "aceito"%}
                <div id='info-perfil'>
                    <a href="{% url 'removerAmigo' usuario.id %}"><div id='editar-perfil'> <p><strong>Remover</strong></p> </div></a>
                </div>
                {% else %}
                <div id='info-perfil'>
                    <a href="{% url 'adicionarAmigo' usuario.id %}"><div id='editar-perfil'> <p><strong>Enviar</strong></p> </div></a>
                </div>
                {% endif %}
            {% endif %}
            <p class='titulos-perfil titulo-projeto'> Projetos <p>
        </div>

        <div id='dados-profile'> 
            <div id='projetos-perfil'>
                <div id='equipes-perfil'>
                    <div class='icone-projetos-perfil'><img src="{% static 'media/icones/ideia.png'%}" alt=""></img></div>
                    <div id='equipe-perfil' >
                        <p> <strong>Projetos</strong> </p>
                        <p class='quantidade-equipes'> <strong>{{projetos.count}}</strong> </p>
                    </div>
                </div>
                <div id='tarefas-perfil'>
                    <div class='icone-projetos-perfil'><img src="{% static 'media/icones/verdadeiro.png'%}" alt=""></img></div>
                    <div id='tarefa-perfil'>
                        <p> <strong>Tarefas</strong> </p>
                        <p class='quantidade-tarefas'> <strong>{{tarefas.count}}</strong> </p>
                    </div>
                </div>
            </div>
            
        </div>
    </div>

    <p class='titulos-perfil'> Amigos ({{ amigos.count }}) <p>
    <div id='amigos-perfil'>
        {% for amigo in amigos %}
            <div class='amigo-perfil'>
                {% if not amigo.receiver.avatar %}
                    <div class='amigo-avatar'><img src="{% static 'media/icones/do-utilizador (2).png' %}" alt=""></div>
                {% else %}
                    <div class='amigo-avatar'><img src="{{ amigo.receiver.avatar.url }}"alt="foto"></div>
                {% endif %}
                <div class='amigo-dados'>
                    <a href="{% url "perfil" amigo.receiver.user.id%}">
                        <h4> {{ amigo.receiver.nome }} {{ amigo.receiver.sobrenome }}  </h4>
                        <p> {{ amigo.receiver.empresa }} </p>
                    </a>
                </div>
                {% if usuario.id == user.id %}
                <a href="{% url 'removerAmigo' amigo.receiver.id %}"><img src="{% static 'media/icones/rejeitar.png'%}" alt=""></a>
                {% else %}
                    <div>  </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <a href="{% url "logout" %}">  
        <div id='logout'> <p> <strong>Logout</strong> </p> </div>
    </a>
</section>
{% endblock %}

templates/usuarios/userProfile.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section id='login'>
    {% for message in messages  %}
    <div class='{{message.tags}}'> 
        <strong>{{message}}</strong>
    </div>
    {% endfor %}
    <div id="header-login">
        <div id='icone-cadastro'> <p><strong>Editar Perfil</strong></p> </div>
    </div>
    <form id='formulario-login'action="{% url 'userProfile'  %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <div>
            {% for field in form.visible_fields %}
            <div class='label-login'>
                <label for="{{orm.id_for_label}}">  
                    {% if field.label == "Nome" %}
                        <img src="{% static 'media/icones/do-utilizador (2).png'%}" alt="">
                    {% elif field.label == "Sobrenome" %}
                        <img src="{% static 'media/icones/do-utilizador (2).png'%}" alt="">
                    
                    {% elif field.label == "Empresa" %}
                        <img src="{% static 'media/icones/maleta-de-negocios.png'%}" alt="">
                    {% elif field.label == "Avatar" %}
                        <img src="{% static 'media/icones/do-utilizador (3).png'%}" alt="">
                    {% endif %}
                </label>
                {{field}}
                </div>
            {% endfor %}
        </div>

        <button id='botao-cadastro' type='submit'> <h2><strong>Editar Perfil</strong></h2></button>    
    </form>
   
</section>
{% endblock %}