Setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tasks.urls')),
    path('',include('usuarios.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  

apps/tasks/urls.py
from django.urls import path
from tasks.views import *

urlpatterns = [
    path("",inicial, name='inicial'),
    path("home", index, name='home'),
    path('filtro/<str:filtro>/<str:valor>/', index, name='filtro'),
    path('buscar',buscar,name='buscar'),
    path('criar/projeto',criarProjeto ,name="criarProjeto"),
    path('novo_projeto',novo_projeto, name='novo_projeto'),
    path('criar/tarefa/<int:projeto_id>',criarTarefa ,name="criarTarefa"),
    path('novo_tarefa/<int:projeto_id>',novo_tarefa, name='novo_tarefa'),
    path('notificações',notificacao ,name="notificações"),
    path('atualizar_status/<str:relacionamento>/<int:notificacao_id>/<str:status>/',atualizar_status, name='atualizar_status'),
    path('convidar/equipe/<int:projeto_id>',convidaEquipe ,name="convidaEquipe"),
    path('remover_equipe/<int:amigo_id>/<int:projeto_id>', removerEquipe, name='remover_equipe'),
    path('cancelar_convite/<int:convite_id>/<int:projeto_id>', cancelarConvite, name='cancelar_convite'),
    path('convidar_amigo/<int:amigo_id>/<int:projeto_id>', convidarAmigo, name='convidar_amigo'),
    path("projeto/<int:projeto_id>", projeto, name='projeto'),
    path('editar/projeto/<int:projeto_id>',editar_projeto ,name="editar_projeto"),
    path('editar/tarefa/<int:tarefa_id>/<int:projeto_id>', editar_tarefa ,name="editar_tarefa"),
    path('excluir/projeto/<int:projeto_id>', excluirProjeto , name='excluirProjeto'),
    path('excluir/tarefa/<int:tarefa_id>/<int:projeto_id>', excluirTarefa , name='excluirTarefa'),
    path('adicionar/<int:projeto_id>/<int:tarefa_id>',MembrosTarefa, name='MembrosTarefa'),
    path('adicionar/equipe/<int:projeto_id>/<int:usuario_id>/<int:tarefa_id>', addMembroTarefa, name='addMembroTarefa'),
    path('remover/equipe/<int:projeto_id>/<int:usuario_id>/<int:tarefa_id>', popMembroTarefa, name='popMembroTarefa'),
]

apps/tasks/models.py
from django.contrib.auth.models import User
from django.db import models
from usuarios.models import UserProfile




STATUS_PROJETO = (
    ('Razoável','Razoável'),
    ('Médio','Médio'),
    ('Alto','Alto'),
)
COR_PROJETO = (
    ('#ff7a7a','Vermelho'),
    ('#fed148','Amarelo'),
    ('#92fc8d','Verde'),
    ('#55adfb','Azul'),
    ('#f592fa','Roxo'),
    ('#cc7aff','Rosa'),
    ('#ffffff','Branco'),
)


class Projeto(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    descricao = models.TextField(max_length=200)
    cor = models.CharField(max_length=8, choices=COR_PROJETO, default=None)
    status = models.CharField(max_length=8, choices=STATUS_PROJETO, default=None)
    data_inicio = models.DateField(default=None)
    data_termino = models.DateField(default=None)
    

    def __str__(self):
        return self.titulo

class Equipe(models.Model):
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)
    usuario = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return f'Equipe {self.usuario}'


class Tarefa(models.Model):
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    descricao = models.TextField()
    data_inicio = models.DateField(default=None)
    data_termino = models.DateField(default=None)
    completa = models.BooleanField(default=False)
    def __str__(self):
        return self.titulo
    
STATUS_CHOICES = (
    ('enviado','Enviado'),
    ('aceito','Aceito'),
    ('recusado','Recusado')
)

class RelationshipEquipe(models.Model):
    usuario = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='usuario', default=None)
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE, related_name='projetos', default=None)
    convidado = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='convidado')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateField(auto_now=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self): 
        return f'{self.projeto}-{self.convidado}-{self.status}'
    
class RelationshipTarefa(models.Model):
    usuario = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='usuario_tarefa', default=None)
    tarefa = models.ForeignKey(Tarefa, on_delete=models.CASCADE, related_name='tarefas', default=None)

    def __str__(self): 
        return f'{self.tarefa}-{self.usuario}'
    

apps/tasks/forms.py
from django import forms
from tasks.models import Projeto, Tarefa

class ProjetoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = Projeto
        labels = {
            'descricao': 'Descrição',
            'data_inicio': 'Data Inicial',
            'data_termino': 'Data Final',
        }
        widgets = {
            'usuario': forms.HiddenInput(),
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control'}),
            'cor': forms.Select(attrs={'class': 'form-control'}),
            'data_inicio': forms.DateInput(attrs={'class': 'form-control'}),
            'data_termino': forms.DateInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
        }
        exclude = ['usuario']

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.usuario = self.user
        if commit:
            instance.save()
        return instance

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        exclude = ['']
        labels = {
            'descricao': 'Descrição',
            'data_inicio': 'Data Inicial',
            'data_termino': 'Data Final',
            'completa':'Completa',
            'projeto':'Projeto',
        }
        widgets = {
            'projeto': forms.Select(attrs={'class': 'form-control'}),
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control'}),
            'data_inicio': forms.DateInput(attrs={'class': 'form-control'}),
            'data_termino': forms.DateInput(attrs={'class': 'form-control'}),
            'completa': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

apps/tasks/views.py
from django.shortcuts import render, redirect , get_object_or_404
from .models import *
from usuarios.models import Relationship
from django.contrib.auth.decorators import login_required
from tasks.forms import ProjetoForm, TarefaForm
from django.contrib import messages


def inicial(request):
    return render(request, "tasks/home.html")


@login_required(login_url='login')
def index(request, filtro=None, valor=None):
    '''Pagina Principal. com Filtros e Informações dos Projetos'''
    user_profile = request.user.userprofile
    todosProjetos = Projeto.objects.filter(equipe__usuario=user_profile)
    usuario = UserProfile.objects.filter(user=request.user)
    notificacaoEquipe = RelationshipEquipe.objects.filter(convidado=user_profile,status='enviado')
    notificacaoAmigo = Relationship.objects.filter(receiver=user_profile, status='enviado')
    notificacao = len(notificacaoEquipe) + len(notificacaoAmigo)
    if filtro == 'cor':
        projetos = Projeto.objects.filter(equipe__usuario=user_profile, cor=valor).order_by('data_termino')
    elif filtro == 'status':
        projetos = Projeto.objects.filter(equipe__usuario=user_profile, status=valor).order_by('data_termino')
    else:
        projetos = Projeto.objects.filter(equipe__usuario=user_profile).order_by('data_termino')
    projetos_com_porcentagem = []
    for projeto in projetos:
        tarefas_completas = Tarefa.objects.filter(projeto=projeto, completa=True).count()
        total_tarefas = Tarefa.objects.filter(projeto=projeto).count()
        porcentagem = int((tarefas_completas / total_tarefas) * 100) if total_tarefas > 0 else 0
        equipe = Equipe.objects.filter(projeto=projeto)
        projetos_com_porcentagem.append((projeto, tarefas_completas, porcentagem, equipe))
    return render(request, 'tasks/tasks.html', 
                {'projetos_com_porcentagem': projetos_com_porcentagem,
                'projetos':todosProjetos,'usuario':usuario, 'notificacao':notificacao })

@login_required(login_url='login')
def buscar(request):
    '''Função de Busca por nome de Projeto'''
    user_profile = request.user.userprofile
    projetos = Projeto.objects.filter(equipe__usuario=user_profile).order_by('data_termino')
    todosProjetos = Projeto.objects.filter(equipe__usuario=user_profile)
    projetos_com_porcentagem = []
    usuario = UserProfile.objects.filter(user=request.user)
    notificacaoEquipe = RelationshipEquipe.objects.filter(convidado=user_profile,status='enviado')
    notificacaoAmigo = Relationship.objects.filter(receiver=user_profile, status='enviado')
    notificacao = len(notificacaoEquipe) + len(notificacaoAmigo)
    if "buscar" in request.GET:
            nome_buscar = request.GET['buscar']
            if nome_buscar:
                projetos = projetos.filter(equipe__usuario=user_profile, titulo__icontains=nome_buscar)   
                for projeto in projetos:
                    tarefas_completas = Tarefa.objects.filter(projeto=projeto, completa=True).count()
                    total_tarefas = Tarefa.objects.filter(projeto=projeto).count()
                    porcentagem = int((tarefas_completas / total_tarefas) * 100) if total_tarefas > 0 else 0
                    equipe = Equipe.objects.filter(projeto=projeto)
                    
                    projetos_com_porcentagem.append((projeto, tarefas_completas, porcentagem, equipe))
        
    return render(request, 'tasks/tasks.html', 
                  {'projetos_com_porcentagem': projetos_com_porcentagem,'notificacao':notificacao,
                    'projetos':todosProjetos,'usuario':usuario})

@login_required(login_url='login')
def projeto(request,projeto_id):
    '''Pagina do Projeto'''
    user_profile = request.user.userprofile
    todosProjetos = Projeto.objects.filter(equipe__usuario=user_profile)
    projeto = get_object_or_404(Projeto, id=projeto_id)
    tarefas = Tarefa.objects.filter(projeto=projeto_id).order_by('data_termino')
    tarefas_completas = Tarefa.objects.filter(projeto=projeto_id, completa=True).count()
    total_tarefas = Tarefa.objects.filter(projeto=projeto_id).count()
    equipe = Equipe.objects.filter(projeto=projeto_id)

    if faz_parte_equipe(equipe, user_profile.id) == False:
        print(equipe,user_profile.id)
        return redirect('home')

    notificacaoEquipe = RelationshipEquipe.objects.filter(convidado=user_profile,status='enviado')
    notificacaoAmigo = Relationship.objects.filter(receiver=user_profile, status='enviado')
    notificacao = len(notificacaoEquipe) + len(notificacaoAmigo)
    usuarioTarefa = RelationshipTarefa.objects.filter(tarefa__projeto=projeto_id)
    return render(request,'tasks/projeto.html',
                   {'projeto':projeto, 'projetos':todosProjetos,'tarefas':tarefas, 
                    'tarefas_completas':tarefas_completas, 'total_tarefas':total_tarefas,
                    'equipe':equipe, 'notificacao':notificacao, 'usuarioTarefa': usuarioTarefa})

# ------------------- Criar Projeto ----------------------

@login_required(login_url='login')
def criarProjeto(request):
    ''' Pagina de Criação de Projeto'''
    user_profile = request.user.userprofile
    todosProjetos = Projeto.objects.filter(equipe__usuario=user_profile)
    projeto = ProjetoForm
    usuario = UserProfile.objects.filter(user=request.user)
    notificacaoEquipe = RelationshipEquipe.objects.filter(convidado=user_profile,status='enviado')
    notificacaoAmigo = Relationship.objects.filter(receiver=user_profile, status='enviado')
    notificacao = len(notificacaoEquipe) + len(notificacaoAmigo)
    return render(request, 'tasks/projetoCreate.html' ,
                  {'form':projeto,'projetos':todosProjetos,'usuario':usuario,
                   'projeto_id':000, 'notificacao':notificacao})

@login_required(login_url='login')
def novo_projeto(request):
    ''' Criação de Projeto '''
    if not request.user.is_authenticated:
        return redirect('login')
    if request.method == 'POST':
        form = ProjetoForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            projeto_id = form.instance.id
            return redirect('criarTarefa', projeto_id)
    else:
        form = ProjetoForm(user=request.user)
    return redirect('criarProjeto')

# ------------------- Criar Tarefa ----------------------

@login_required(login_url='login')
def criarTarefa(request, projeto_id=None):
    '''Pagina de Criação de Tarefa'''
    user_profile = request.user.userprofile
    todosProjetos = Projeto.objects.filter(equipe__usuario=user_profile)
    ultimo_projeto = Projeto.objects.filter(usuario=request.user).latest('id')
    notificacaoEquipe = RelationshipEquipe.objects.filter(convidado=user_profile,status='enviado')
    notificacaoAmigo = Relationship.objects.filter(receiver=user_profile, status='enviado')
    notificacao = len(notificacaoEquipe) + len(notificacaoAmigo)
    if projeto_id is not None:
        projeto = get_object_or_404(Projeto, id=projeto_id, equipe__usuario=user_profile)
        tarefa = TarefaForm(initial={'projeto': projeto})
        return render(request, 'tasks/tarefaCreate.html',
                   {'form': tarefa, 'projetos': todosProjetos,
                    'tarefa_id':000, 'notificacao':notificacao, 'projeto_id':projeto_id})
    else:
        tarefa = TarefaForm(initial={'projeto': ultimo_projeto})
   
    return render(request, 'tasks/tarefaCreate.html',
                   {'form': tarefa, 'projetos': todosProjetos,
                    'tarefa_id':000, 'notificacao':notificacao})

@login_required(login_url='login')
def novo_tarefa(request, projeto_id):
    '''Criação de Tarefa'''
    if not request.user.is_authenticated:
        return redirect('login')
    if request.method == 'POST':
        form = TarefaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Tarefa Criada!")
            return redirect('projeto', projeto_id)
    else:
        form = ProjetoForm(user=request.user)
    return redirect('criarTarefa', projeto_id)


# ------------------- Notificações ----------------------


@login_required(login_url='login')
def notificacao(request):
    '''Notificações de Projetos e Amizidades'''
    user_profile = request.user.userprofile
    todosProjetos = Projeto.objects.filter(equipe__usuario=user_profile)
    notificacaoEquipe = RelationshipEquipe.objects.filter(convidado=user_profile,status='enviado')
    notificacaoAmigo = Relationship.objects.filter(receiver=user_profile, status='enviado')
    notificacaoEquipe = RelationshipEquipe.objects.filter(convidado=user_profile,status='enviado')
    notificacaoAmigo = Relationship.objects.filter(receiver=user_profile, status='enviado')
    notificacao = len(notificacaoEquipe) + len(notificacaoAmigo)
    return render(request, 'usuarios/notificacao.html', 
                  { 'projetos':todosProjetos,'notificacaoAmigo': notificacaoAmigo,
                   'notificacaoEquipe': notificacaoEquipe,'notificacao':notificacao })

@login_required(login_url='login')
def atualizar_status(request, relacionamento, notificacao_id, status):
    ''' Escolha de Notificação - AMIZADA ou PROJETO (Recusar ou Aceitar)'''
    if relacionamento == 'relationship':
        notificacao = get_object_or_404(Relationship, id=notificacao_id)
        if status == 'aceito' or 'recusado':
            notificacao.status = status
            notificacao.save()

    elif relacionamento == 'relationship_equipe':
        notificacao = get_object_or_404(RelationshipEquipe, id=notificacao_id)
        if status == 'aceito' or 'recusado':
            notificacao.status = status 
            notificacao.save()
    else:
        return redirect('notificações')
    return redirect('notificações')

# ------------------- Projeto ----------------------


@login_required(login_url='login')
def convidaEquipe(request, projeto_id):
    ''' Pagina para convidar amigo para projeto'''

templates/tasks/equipe.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section id='equipes'>
    
    <h2> Equipe</h2>
    <a href="{% url 'projeto' projeto_id %}"><img style='margin:10px' src="{% static 'media/icones/botao-voltar.png' %}" alt=""></a>
    <!-- Amigos que aceitaram o convite -->
    <h3>Equipe</h3>
    {% for membro in equipe %}
                <div class='perfil-equipe'>
                    <div class='dados-equipe'>
                        <div id="icone-equipe">
                            {% if not membro.usuario.avatar %}
                                <img src="{% static 'media/icones/do-utilizador (2).png' %}" alt="">
                            {% else %}
                            <img src="{{ membro.usuario.avatar.url }}" alt="foto">
                            {% endif %}
                        </div>
                        <div class='info-amigo'>
                            <a href="{% url "perfil" membro.usuario.user.id %}"> 
                                <p><strong>{{ membro.usuario.nome }}</strong></p>
                                <p>{{ membro.usuario.empresa }}</p>
                            </a>
                        </div>
                        <a href="{% url 'remover_equipe' membro.usuario.id projeto_id %}"><div class='btn-equipe'> <strong>Remover</strong> </div></a>
                    </div>
                </div>
    {% endfor %}
    
    <!-- Amigos com convite pendente -->
    <h3>Enviado</h3>
    {% for convite in convites %}
        {% if convite.status == 'enviado' %}
            <div class='perfil-equipe'>
                <div class='dados-equipe'>
                    <div id="icone-equipe">
                        {% if not convite.convidado.avatar %}
                            <img src="{% static 'media/icones/do-utilizador (2).png' %}" alt="">
                        {% else %}
                        <img src="{{ convite.convidado.avatar.url }}" alt="foto">
                        {% endif %}
                    </div>
                    <div class='info-amigo'>
                    <a href="{% url "perfil" convite.convidado.user.id %}">
                        <p><strong>{{ convite.convidado.nome }}</strong></p>
                        <p>{{ convite.convidado.empresa }}</p>
                    </a>
                    </div>
                    
                    <a href="{% url 'cancelar_convite' convite.id projeto_id %}"><div class='btn-equipe'> <strong>Cancelar</strong> </div></a>

                </div>
            </div>
        {% endif %}
    {% endfor %}
    
    <!-- Amigos que ainda não foram convidados -->
    <h3>Convidar</h3>
    {% for amigo in amigos_nao_convidados %}
        <div class='perfil-equipe'>
            <div class='dados-equipe'>
                <div id="icone-equipe">
                    {% if not amigo.avatar %}
                        <img src="{% static 'media/icones/do-utilizador (2).png' %}" alt="">
                    {% else %}
                        <img src="{{ amigo.receiver.avatar.url }}" alt="foto">
                    {% endif %}
                </div>
                <div class='info-amigo'>
                    <a href="{% url "perfil" amigo.receiver.user.id %}"> 
                        <p><strong>{{ amigo.receiver.nome }}</strong></p>
                        <p>{{ amigo.receiver.empresa }}</p>
                    </a>
                </div>
                <a href="{% url 'convidar_amigo' amigo.receiver.id projeto_id %}"><div class='btn-equipe'> <strong>Convidar</strong> </div></a>

            </div>
        </div>
    {% endfor %}
    
</section>

{% endblock %}

templates/tasks/projetoCreate.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

{% if projeto_id != 000 %}
<div class='titulo'>
    <h2> Editar Projeto</h2>
</div>
<section id='formulario'>
    <form action="{% url 'editar_projeto' projeto_id %}" method="POST" enctype="multipart/form-data">
{% else %}
<div class='titulo'>
    <h2 >Criar Projeto</h2>
</div>
<section id='formulario'>
    <form action="{%url 'novo_projeto'  %}" method='POST' enctype='multipart/form-data'> 
    {% endif %}
        {% csrf_token %}
        <div>
            <div class='texts'>
                {% for field in form.visible_fields  %}
                    {% if field.label == 'Titulo' %}
                        <label for="{{ orm.id_for_label}}">
                            <div class='labels'><p><strong>{{ field.label }}:</strong></p></div>
                        </label>
                        <div class='titulos'>{{ field }}</div>
                    {% elif field.label == 'Descrição' %}
                        <label for="{{ orm.id_for_label}}">
                            <div class='labels'><p><strong>{{ field.label }}:</strong></p></div>
                        </label>
                        <div class='descricao'>{{ field }}</div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class='selecionar'>
            {% for field in form.visible_fields  %}
                {% if field.label == 'Cor' %}
                    <div id='cores'>
                        <label for="{{ orm.id_for_label}}">
                        <div class='labels'><p><strong>{{ field.label }}</strong></p></div>
                        </label>
                        <select name="cor" class="form-control" id="id_cor">
                            <option value="#ff7a7a" style="background-color: #ff7a7a; color: white;">Vermelho</option>
                            <option value="#fed148" style="background-color: #fed148; color: white;">Amarelo</option>
                            <option value="#92fc8d" style="background-color: #92fc8d; color: white;">Verde</option>
                            <option value="#55adfb" style="background-color: #55adfb; color: white;">Azul</option>
                            <option value="#f592fa" style="background-color: #f592fa; color: white;">Roxo</option>
                            <option value="#cc7aff" style="background-color: #cc7aff; color: white;">Rosa</option>
                        </select>
                    </div>
                {% elif field.label == 'Status'%}
                    <div id='status'>
                        <label for="{{ orm.id_for_label}}">
                            <div class='labels'><p><strong>{{ field.label }}</strong></p></div>
                        </label>
                        {{ field }}
                    </div>
                {% endif %}
            {% endfor %}
            </div>
            <div class='datas'>
            {% for field in form.visible_fields  %}
                {% if field.label == 'Data Inicial' %}
                    <div id='data_inicial'>
                        <label for="{{ orm.id_for_label}}">
                        <div class='labels'><p><strong>{{ field.label }}</strong></p></div> </label>
                        <input type="date" name="data_inicio" class="form-control" required="" id="id_data_inicio">
                    </div>
                    {% elif field.label == 'Data Final'%}
                        <div id='data_final'>
                            <label for="{{ orm.id_for_label}}">
                            <div class='labels'><p><strong>{{ field.label }}</strong></p></div> </label>
                            <input type="date" name="data_termino" class="form-control" required="" id="id_data_termino">
                        </div>
                    {% endif %}
            {% endfor %}
            </div>
            {% if projeto_id != 000 %}
                <button type="submit" class='botao_criar'> <strong>Editar Projeto</strong></button>
            {% else %}
                <button type="submit" class='botao_criar'> <strong>Criar Projeto</strong></button>
            {% endif %}
        </div>
    </form>
</section>    
{% endblock %}

templates/tasks/tarefaCreate.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
{% if tarefa_id != 000 %}
<div class='titulo'>
    <h2 >Editar Tarefa</h2>
</div>
<section id='formulario'>
    <form action="{% url 'editar_tarefa' tarefa_id projeto_id %}" method='POST' enctype='multipart/form-data'>    
{% else %}
<div class='titulo'>
    <h2 >Criar Tarefa</h2>
</div>
<section id='formulario'>
    <form action="{% url 'novo_tarefa' projeto_id %}" method='POST' enctype='multipart/form-data'>    
{% endif %}
        {% csrf_token %}
        <div>
            {% for field in form.visible_fields  %}
                    {% if field.label == 'Projeto' %}
                    <label for="{{ orm.id_for_label}}">
                        <div class='labels'><p><strong>{{ field.label }}:</strong></p></div>
                    </label>
                    <div class='projetos-select'>{{ field }}</div>
                    {% elif field.label == 'Titulo' %}
                        <label for="{{ orm.id_for_label}}">
                            <div class='labels'><p><strong>{{ field.label }}:</strong></p></div>
                        </label>
                        <div class='titulos'>{{ field }}</div>
                    {% elif field.label == 'Descrição' %}
                        <label for="{{ orm.id_for_label}}">
                            <div class='labels'><p><strong>{{ field.label }}:</strong></p></div>
                        </label>
                        <div class='descricao'>{{ field }}</div>
                    {% endif %}
            {% endfor %}
            <div class='datas'>
            {% for field in form.visible_fields  %}
                {% if field.label == 'Data Inicial' %}
                    <div id='data_inicial'>
                        <label for="{{ orm.id_for_label}}">
                        <div class='labels'><p><strong>{{ field.label }}</strong></p></div> </label>
                        <input type="date" name="data_inicio" class="form-control" required="" id="id_data_inicio">
                    </div>
                    {% elif field.label == 'Data Final'%}
                        <div id='data_final'>
                            <label for="{{ orm.id_for_label}}">
                            <div class='labels'><p><strong>{{ field.label }}</strong></p></div> </label>
                            <input type="date" name="data_termino" class="form-control" required="" id="id_data_termino">
                        </div>
                    {% endif %}
            {% endfor %}
            </div>
            {% for field in form.visible_fields  %}
                {% if field.label == 'Completa' %}
                <div class='completa'>
                    <label for="{{ orm.id_for_label}}">
                        <div class='labels'><p><strong>{{ field.label }}:</strong></p></div>
                    </label>
                    <div>{{ field }}</div>
                </div>
                {% endif %}
            {% endfor %}
            <br>
            {% if tarefa_id != 000 %}
                <button type="submit" class='botao_criar'> <strong>Editar Tarefa</strong></button>
            {% else %}
                <button type="submit" class='botao_criar'> <strong>Criar Tarefa</strong></button>
            {% endif %}
        </div>
    </form>
</section>    
{% endblock %}